language: node_js
node_js:
- '7'
- '8'
- '9'
- '10'
notifications:
  slack:
    secure: D4+aUEYvjJO8qlIhlJts3m3WIUb4poeeEoovSyDv9dm9rVDNnAqkwDG1TEts5icfCvz5e6abcHNYnmBgz/LtiwTxvtgKBXqMrcLc9jA53mAVeL8gr+5fqwYP8tPG38Fw9umBmgIsYTD7usnWaMFbbMQjY/m4F7Zs6DlWB5dpDtrhxhVt3Hws4tOGh9Gh56VPvaun2lJxooJKJv4P0VTOi2dx2ujPY0gNYIIeYd7lkZC0tQToas9+6vJcIBU+44AeT4qtr0HrVQpExYzQwzoCcWU2Ge0Jg8QqE/kSYZxuu5eZsdL+o315EPElk9hW4S+TaWI/wxrJf6CIbk4pvmIf6Pqa3SVTCZGjlNNProOCKq/+ub3wBMAzv+Z1UkCmlodqqyYq0M4ZGNxxwv3VZZPlsInpBG3f3Yeem1WpWp7Rjl0MWWvwOVCcg5336oKJ9f3CGNzj82WWIITwepFnvCsUlbg1Paf1Q3Ld1tHZ3brbs1R0YHGkxllcPOB5wmdNRf9ePaBDkCEwPzp4zr0EfjLFUCNjfB1fQ8nUXId8/Hin3LfBAvw9U4oBVy50vpvRWfWEG3HB4b2iecBCfU5VnYgq0GUpzLbUWF203X9XBQ1A5PQwYtRLGv0Yb/mSRf1UQEBezecidvYpxOMgpTHLXKgkKK5+BCr7PEA5odVCk6hW0QQ=
